### ISSUE TITLE
Improvement

### ISSUE THREAD

**Issue by Ethal** [mika-nt28/Jeedom-luminotherapie#3]
https://github.com/mika-nt28/Jeedom-luminotherapie/blob/877fe11289a1d898650174d81123c47b2ae0c69c/core/class/luminotherapie.class.php#L94

Bonsoir,
je ne suis pas pour les "sleep" , tu blocs ton code et celui des autres plugins

**Comment by mika-nt28** [comment]
c'est un démon donc il ne bloque pas jeedom bien au contraire il lierre des ressource
