### ISSUE TITLE
Liens des Changelog et Documentation ne semble pas à jour

### ISSUE THREAD

**Issue by BadWolf42** [mika-nt28/Jeedom-luminotherapie#31]
Infos à mettre à jour dans info.json :
Changelog : https://github.com/mika-nt28/Jeedom-luminotherapie/commits/stable
Doc : https://github.com/mika-nt28/Jeedom-luminotherapie/blob/stable/doc/fr_FR/index.asciidoc

**Comment by mika-nt28** [comment]
Effectivement j'ai oublié de mettre a jours l'url du changelog.
Par contre l'url de la doc doit rester sur le site officiel de jeedom, il faut que je regarde pourquoi elle ne se met pas a jours
