### ISSUE TITLE
L'affichage des "ambiances" ne fonctionnent plus

### ISSUE THREAD

**Issue by Smaky07** [mika-nt28/Jeedom-luminotherapie#37]
Le commit 7bf74a88a0e132289346d3d77c990b093bacc2cc n'est pas bon et bloque l'affichage des ambiances.
La ligne AmbianceArray.Configuration= new Array(); est en erreur car AmbianceArray n'est pas un objet.
J'ai fait un revert sur le commit et avec juste la ligne var AmbianceArray= new Object(); tout fonctionne.

**Comment by mika-nt28** [comment]
Effectivement.
Je regarde ca

**Comment by mika-nt28** [comment]
Erreur de debutant
C'est corriger
